PASSWORD = "BLACKJACK69"

NICK_TYPE = "nick"

MESSAGE_TYPE_LENGTH = 4
MESSAGE_LENGTH_FORMAT = 3

GAME_INFO = "LBIN"
LOBBY_JOIN_RESPONSE = "LBJN"
CAN_GAME_START = "CNGS"
GAME_STARTED_INIT = "GMST"
GAME_ENDING = "GMEN"
JOIN_TYPE = "JOIN"
START_THE_GAME = "PLAY"
TURN = "TURN"
