PASS = "420BJ69"

FORMAT_LEN = 3
CMD_LEN = 4

NICK = "NICK"
PING = "PING"
PONG = "PONG"
GAME_INFO = "GMIF"
LOBBY_JOIN_RESPONSE = "GMJN"
CAN_GAME_START = "GMCK"
GAME_STARTED_INIT = "GMST"
GAME_ENDING = "GMEN"
JOIN_TYPE = "JOIN"
START_THE_GAME = "PLAY"
TURN = "TURN"
NEXT_ROUND = "NEXT"
PING_INTERVAL = "PNIT"
RETRIEVING_STATE = "RETR"
GAME_STOP = "STOP"
PLAYER_STATE = "STAT"
OCCUPIED_NICK = "OCNI"
KILL = "KILL"
KILL2 = "KIL2"

TIMEOUT_LIMIT = 30
TIMEOUT = 10
